"""
DnD Session report API tool

This is a tie in with the DnD session transcriber that I have developed in Spyder on the main system (Pending addition to the Git for this project)
This segment of the codebase is meant to take the summary that gets generated by the summarizer tool (which is on the TO-Do list, and wil likely start as a GPT-4o plug)
and transefer them into a series of session reports on the WA, which should help with continuity. 

Dev: Deven Nieves-Noel 
10/25/24 

There are some helpful rescources from the WA discord linked below:

Current Documentation: https://www.worldanvil.com/api/external/boromir/documentation

Current API Python wrapper: https://gitlab.com/SoulLink/world-anvil-api-client

Current (personal) API token "9TaQa6Z37R2ApLy4F9bZbNo0UyYRtPtBejkZGkwykSPHQpAdFFwmmTMZOGmvERWHJcdkqA7YNLM2RMOGWyBpfEhBx68g2B9vKwPDsPeZmmg2HGor2bC0kbQtJFzpDmSF5Jc0JWssvAA4pzMtKeHnhQLq9ffIdtfPEaz5pZowNOw6hC2It6K2UocykUXuyqAQkRXtJFc1U8nuVqNbb5FD1hSOmOcniUukLAmNjDJPG0KPCSn62BlnhmWI1"

"""
#import block
import os
from pywaclient.api import BoromirApiClient


session_report_article = client.article.put({
    #Title for the article
    'title': "A test of the Code Article Builder",
    #The display state of the article
    'state': "Private",
    #The world for it to go in, it references line 47-48, id is a lookup for a param in the dictionary that line 48 provides, it gives world id 
    'world': {
        'id': worlds[0]['id']
    },
    #template type for the article to be generated
    'templateType': 'report'
})
