"""
DnD Session report API tool

This is a tie in with the DnD session transcriber that I have developed in Spyder on the main system (Pending addition to the Git for this project)
This segment of the codebase is meant to take the summary that gets generated by the summarizer tool (which is on the TO-Do list, and wil likely start as a GPT-4o plug)
and transefer them into a series of session reports on the WA, which should help with continuity. 

Dev: Deven Nieves-Noel 
10/25/24 

There are some helpful rescources from the WA discord linked below:

Current Documentation: https://www.worldanvil.com/api/external/boromir/documentation

Current API Python wrapper: https://gitlab.com/SoulLink/world-anvil-api-client

"""
#import block
import os
from pywaclient.api import BoromirApiClient

def Push_Article(ai_Output):

    client = BoromirApiClient(
    #Project Name
    'Test_script_1', 
    #Github Project URL
    "nourl_yet", 
    #Project Version
    'V0',
    #API Key supplied by WA saff
    '073a7c2deeffd2c94244f78fce44036aae2f34d54dd27e5719eff88b9c9b85ff8bd1442ce8986d81dc082cfa397a7b7879b4a6e7c7a60bfe3b0c6b0a8e2024c0',
    #Api User authentication token generated by the user in the world
    '9TaQa6Z37R2ApLy4F9bZbNo0UyYRtPtBejkZGkwykSPHQpAdFFwmmTMZOGmvERWHJcdkqA7YNLM2RMOGWyBpfEhBx68g2B9vKwPDsPeZmmg2HGor2bC0kbQtJFzpDmSF5Jc0JWssvAA4pzMtKeHnhQLq9ffIdtfPEaz5pZowNOw6hC2It6K2UocykUXuyqAQkRXtJFc1U8nuVqNbb5FD1hSOmOcniUukLAmNjDJPG0KPCSn62BlnhmWI1'
    )

    authenticated_user = client.user.identity()

    # get the references to all the worlds on your account.
    worlds = [world for world in client.user.worlds(authenticated_user['id'])]

    new_test_article = client.article.put({
        #Title for the article
        'title': "Session Test 11-22-24",
        #The display state of the article
        'state': "Private",
        'isWip': True, 
        'isDraft': True, 
        'icon': " ra-quill-ink",
        'Excerpt': "This is an AI generated summary of the Session, there are likley errors, if you see anny please reach out to your DM",
        'allowComments': True,
        'content': ai_Output,

        "displayCss": """
        /* Parchment background and styling */
        .parchment-style {
            background-image: Parchment Texture.jpg; 
            background-size: cover; 
            background-repeat: no-repeat; 
            padding: 20px; 
            border: 1px solid #d4bfa4; 
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); 
            color: #4b2e05;
            font-family: 'Georgia', serif;
            line-height: 1.6;
        }

        /* Heading styles for medieval look */
        .parchment-style h1, .parchment-style h2, .parchment-style h3 {
            font-family: 'Cinzel Decorative', serif; 
            color: #6d4c41;
            text-shadow: 1px 1px #d4bfa4;
        }

        /* Add a soft border effect */
        .parchment-style {
            border-radius: 5px;
        }
    """,

    "cssClasses": "parchment-style",

        #The world for it to go in, it references line 47-48, id is a lookup for a param in the dictionary that line 48 provides, it gives world id 
        'world': {
            'id': worlds[0]['id']
        },
        #template type for the article to be generated
        'templateType': 'report'
    }) 
