# -*- coding: utf-8 -*-
"""
Created on Thu Oct 19 16:03:39 2023

@author: rebel
"""

import sqlite3



def DbtoDict():
    """

    Returns dict (dictionary of names with no values)
    -------
    name_dict : None
        DESCRIPTION:
            This is a function to gather the names in the database 
            generated by the DBMaker file and put them into a dictionary for faster access
            
            I may use the counts to program prevalence later
            
            I may specify this as an actual hash table at some point

    """
    
    #opens the database
    db_file = 'DnD_Namer1.db'
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()
    
    #Quiery the database for the name
    query = "SELECT Childs_First_Name FROM DnD_Namer1"
    cursor.execute(query)
    #results becomes a list of tuples
    results = cursor.fetchall()
    
    if results:
        #creates a python dictionary with all the names
        name_dict = {}
        i = 0 
        for result in results: 
            name = result[0]
            #Use the name as a key and assign a placeholder value
            name_dict[i] = name
            i += 1 
            
            
    else: 
        print("results empty, big sad")
        
    conn.close()
    
    return name_dict 

